## 3.3 Eliminação de Gauss-Jordan e matriz inversa

Os métodos diretos de eliminação consistem no processo 
de transformar um sistema de equações lineares $Ax=b$, em que $A= (a_{ij})_i,j=1,..,n$, 
$x=(x_1,x_2,...,x_n)^t$ e $b=(b_1, b_2,...,b_n)^t$, em um sistema equivalente, 
aplicando operações elementares sobre as linhas da matriz $(A,b)$.

O sistema equivalente obtido ao final do processo, deve ser de 
resolução mais simples ou imediata, por substituição direta. No caso da eliminação de Gauss 
com pivoteamento diagonal ou pivoteamento parcial, obtém-se um sistema equivalente 
na forma triangular. No caso da eliminação de Gauss-Jordan o sistema equivalente 
obtido possui a matriz de coeficientes igual a matriz identidade.   


Em geral, consideraremos neste texto, um sistema linear escrito na forma geral como  

$$ \begin{cases} 
	         a_{11}x_1 +a_{12}x_2 + \cdots + a_{1n}x_n = b_1\\ 
	         a_{21}x_1 +a_{22}x_2 + \cdots + a_{2n}x_n = b_2\\
	         \vdots   \\
	         a_{n1}x_1 +a_{n2}x_2 + \cdots + a_{nn}x_n = b_1\\
	         \end{cases} $$
             
cuja forma forma matricial $Ax=b$ tem a seguinte representação
            
$$\left[\begin{array}{cccc} 
	         a_{11} & a_{12} & \cdots & a_{1n} \\ 
	         a_{21} & a_{22} & \cdots & a_{2n} \\
	         \vdots & \vdots & \vdots & \vdots \\
	         a_{n1} & a_{n2} & \cdots & a_{nn} \\
	         \end{array} \right]
\left[\begin{array}{c} 
	         x_1 \\ 
	         x_2 \\
             \vdots\\
	         x_n \\
	         \end{array} \right]
=
\left[\begin{array}{c} 
	         b_1 \\ 
	         b_2 \\
             \vdots\\
	         b_n \\
	         \end{array} \right]
	         $$
	         
e a matriz aumentada $(A,b)$ é dada por  

$$\left[\begin{array}{cccccc} 
	         a_{11} & a_{12} & \cdots & a_{1n} & | & b_1\\ 
	         a_{21} & a_{22} & \cdots & a_{2n} & | & b_2\\
	         \vdots & \vdots & \vdots & \vdots & | & \vdots\\
	         a_{n1} & a_{n2} & \cdots & a_{nn} & | & b_n\\
	         \end{array} \right]$$
	         



O processo de **eliminação de Gauss** com pivoteamento diagonal consiste em transformar 
o sistema em um sistema equivalente triangular superior por meio de operações 
elementares sobre as linhas da matriz $(A,b)$ tomando, em cada passo, como pivô,
os elementos da diadonal de $A$, desde que não seja nulo. Caso o algum elemento da 
diagonal seja nulo podemos permutar duas linhas da matriz a fim obter um pivô 
diferente de zero.

Para cada passo $k$ do processo, anulamos os termos abaixo do 
elemento da diagonal $a_{kk}$, subtraindo cada linha $i=k+1$ da matriz $(A,b)$, 
pela linha linha anterior, $i=k$, multiplicada pelo fator $m_{ik}=\frac{a_{ik}}{a_{kk}}$.

Assim, no 1º passo ($k=1$), fazemos $m_{i1}=\frac{a_{i1}}{a_{k1}}$, $i=2,...,n$ 
e cada linha de $(A,b)$, a partir da 2ª, será subtraída da 1ª linha multiplicada por
$m_{k1}$ obtendo-se a matriz $(A^{(1)},b^{(1)})$ tal que


$$(A^{(1)},b^{(1)}) = \left[\begin{array}{ccccccc} 
	         a^{(1)}_{11} & a^{(1)}_{12} & a^{(1)}_{13} & \cdots & a^{(1)}_{1n} & | & b^{(1)}_1\\ 
	         0            & a^{(2)}_{22} & a^{(2)}_{23} & \cdots & a^{(2)}_{2n} & | & b^{(2)}_2\\
	         0            & a^{(2)}_{32} & a^{(2)}_{33} & \cdots & a^{(2)}_{3n} & | & b^{(2)}_3\\
	         \vdots       & \vdots       & \vdots       & \vdots & \vdots       & | & \vdots   \\
	         0            & a^{(2)}_{n2} & a^{(2)}_{n3} & \cdots & a^{(2)}_{nn} & | & b^{(2)}_n\\
	         \end{array} \right]$$
             

No 2º passo ($k=2$), fazemos $m_{i2}=\frac{a_{i2}}{a_{k2}}$, $i=3,...,n$ 
e cada linha de $(A^{(1)},b^{(1)})$, a partir da 3ª, será subtraída da 2ª linha multiplicada por
$m_{k2}$ obtendo-se a matriz $(A^{(2)},b^{(2)})$ tal que

$$(A^{(2)},b^{(2)}) = \left[\begin{array}{ccccccc} 
	         a^{(1)}_{11} & a^{(1)}_{12} & a^{(1)}_{13} & \cdots & a^{(1)}_{1n} & | & b^{(1)}_1\\ 
	         0            & 0            & a^{(2)}_{23} & \cdots & a^{(2)}_{2n} & | & b^{(2)}_2\\
	         0            & 0            & a^{(3)}_{33} & \cdots & a^{(3)}_{3n} & | & b^{(3)}_3\\
	         \vdots       & \vdots       & \vdots       & \vdots & \vdots       & | & \vdots   \\
	         0            & 0            & a^{(3)}_{n3} & \cdots & a^{(3)}_{nn} & | & b^{(3)}_n\\
	         \end{array} \right]$$

Segundo os passos seguintes, até o passo $n-1$, obtemos ou sistema triangular superior na forma   
 
$$ \begin{cases} 
	         a^{(1)}_{11}x_1 + a^{(1)}_{12}x_2 + a^{(1)}_{13}x_2 + \cdots + a^{(1)}_{1n}x_n = b^{(1)}_1\\ 
             \hspace{65px}     a^{(2)}_{22}x_2 + a^{(2)}_{23}x_2 + \cdots + a^{(2)}_{2n}x_n = b^{(2)}_2\\ 
             \hspace{65px}     \hspace{65px}     a^{(3)}_{33}x_2 + \cdots + a^{(3)}_{3n}x_n = b^{(3)}_3\\ 
 	         \hspace{65px}     \hspace{65px}      \hspace{65px}     \hspace{45px}      \vdots   \\
	         \hspace{65px}     \hspace{65px}      \hspace{65px}     \hspace{45px}  a^{(n)}_{nn}x_n = b^{(n)}_n\\ 
	         \end{cases} $$

O qual pode ser resolvido por substituição retroativa.



**Exemplo 3.3.1:** Um exemplo de algoritmo para resolver sistemas lineares por eliminação de Gauss.

In [2]:
import numpy as np
from numpy import dot
def gaussElimin(a,b): 
    n = len(b) 
    for k in range(0,n-1): 
        for i in range(k+1,n): 
            if a[i][k] != 0.0: 
                lam = a [i][k]/a[k][k] 
                a[i][k+1:n] = a[i][k+1:n] - lam*a[k][k+1:n] 
                b[i] = b[i] - lam*b[k] 
    for k in range(n-1,-1,-1): 
        b[k] = (b[k] - dot(a[k][k+1:n],b[k+1:n]))/a[k][k] 
    return b

In [20]:
A = np.array([[3.,2.,4.],
     [1.,1.,2.],
     [-4.,3.,2.]])
b = np.array([1., 2., 3.])

x = gaussElimin(A.copy(),b.copy())

In [21]:
np.hstack([A, b.reshape(3, 1)])

array([[ 3.,  2.,  4.,  1.],
       [ 1.,  1.,  2.,  2.],
       [-4.,  3.,  2.,  3.]])

### Método Gauss-Jordan e matriz inversa

Considere o sistema de $n$ equações e $n$ variáveis dado por 

$$ Ax=b$$

Se a matriz $A$ dos coeficientes for não singular, ou seja, se o sistema possuir solução única a matriz é invertível e a solução do sistema pode ser obtida multiplicando-se a inversa $A^{-1}$ à esquerda de ambos os lados da equação, como segue: 

$$A^{-1}Ax=A^{-1}b$$
logo
$$Ix = A^{-1}b$$
ou
$$x = A^{-1}b$$
Que é a solução do sistema linear.

**Exemplo 3.3.2:** Resolver o sistema $Ax=b$ com $A = 
 \left[\begin{array}{ccc} 
	         3 & 0 & 1 \\ 
	         3 & 2 & 1 \\
            -3 & 1 & 3 \\
	     \end{array} \right]$
e $b = (1,1,3)^t$.   

In [5]:
A = np.array([[3,0,1],[3,2,1],[-3,1,3]])
b = np.array([1,1,3])
x = np.dot(np.linalg.inv(A),b)
print (np.round(x,4))

[0. 0. 1.]


A obtenção inversa pode ser feita pelo processo de eliminação de Gauss-Jordan em que são realizadas operações elementares sobre as linhas da matriz $A$ até que ela se torne uma matriz identidade. Essas mesmas operações são realizadas em uma matriz identidade de mesma ordem, ao final das operações na matriz identidade o resultado é a inversa da matriz $A$. O exemplo a seguir implementa o processo de eliminação de Gauss-Jordan.

**Exemplo:** Vamos nesse exemplo utilizar o processo de eliminação de Gauss-Jordan para obter a matriz inversa de 
$A = 
 \left[\begin{array}{ccc} 
	         2 & 1 & 3 \\ 
	         0 & -1 & 1 \\
            1 & 0 & 3 \\
	     \end{array} \right]$

In [30]:
def gaussJordan(M):
    n = len(M)
    for k in range(n):
        M[k] = M[k]/M[k,k]
        for i in range(n):
            if i!=k:
                M[i] = M[i] - M[i,k]*M[k]
    return (M)

A = np.array([[2,1,3],[0,-1,1],[1,0,3]], float)
I = np.identity(len(A))
M = np.concatenate((A,I), axis=1)

print ('Matriz ampliada:')
print (M)

print ('Matriz após eliminação:')
Mgj = gaussJordan(M)
print (Mgj )

print ('Matriz inversa:')
Ainv = Mgj[:,3:6]
print(Ainv)

Matriz ampliada:
[[ 2.  1.  3.  1.  0.  0.]
 [ 0. -1.  1.  0.  1.  0.]
 [ 1.  0.  3.  0.  0.  1.]]
Matriz após eliminação:
[[ 1.   0.   0.   1.5  1.5 -2. ]
 [ 0.   1.   0.  -0.5 -1.5  1. ]
 [ 0.   0.   1.  -0.5 -0.5  1. ]]
Matriz inversa:
[[ 1.5  1.5 -2. ]
 [-0.5 -1.5  1. ]
 [-0.5 -0.5  1. ]]


**1.** Obtenha, caso exista, a solução para os seguintes sistemas lineares utilizando os métodos estudados (eliminação de Gauss, eliminação de Gauss-Jordan, decomposição LU e Matriz inversa).


a) $\begin{cases} 
	         2x_1 + 3x_2 + x_3 +5x_4= 11\\ 
	         x_1  + 3.5x_2  + x_3 +7.5x_4= 13\\
	         1.4x_1 + 2.7x_2 + 5.5x_3 + 12x_4 = 21.6\\
	         -2x_1 + 1x_2 + 3x_3 +28x_4 = 30
	         \end{cases}$
    
b) $\begin{cases} 
	         6.1x_1 + 0.32x_2 + 1.3x_3 +2.1x_4 + 0.11x_5 = 19.52\\ 
	         0.82x_1  + 8.81x_2  + 1.01x_3 +3x_4 + 3.12x_5= 15.83\\
	         0.5x_1 + 1.78x_2 + 15.2x_3 + 4.2x_4 +8.1x_5= -22.14\\
	         4.2x_1 + 5.3x_2 + 1.8x_3 +20.9x_4 +7.51x_5 = 27.28\\
	         0.2x_1 + 9.1x_2 + 4.68x_3 +4.3x_4 +20.1x_5  = -21.78
	         \end{cases}$
             
c)$ \begin{cases} 
    12.1756 x_1 + 4.0231 x_2 - 2.1732 x_3 + 5.1967 x_4 = 17.1020\\ 
   -4.0231 x_1 + 6.0030 x_2              + 1.1973 x_4 = -6.1593\\
   -1.0000 x_1 - 5.2107 x_2 + 11.1111 x_3              =  3.0004\\
	6.0235 x_1 + 7.0000 x_2 +            - 14.1561 x_4 =  0.0000
\end{cases} $

In [52]:

# função para sistema triangular inferior
def solve_tril(L,b):
    y = np.empty(len(b))
    for i in range(len(b)): 
        y[i] = (b[i] - np.dot(L[i,0:i],y[0:i]))/L[i][i] 
    return y

# função para sistema triangular superior
def solve_triu(U,y):
    n=len(y)
    x = np.empty(n)
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.sum(U[i,i+1:n+1]*x[i+1:n+1]))/U[i,i]
    return x

def fatoraLU(A):
    L = np.eye(len(A))
    U = A.copy()
    n = len(A)
    for j in range(n-1):
        for i in range(j,n-1):            
            m = U[i+1,j]/U[j,j]
            U[i+1] = U[i+1]-m*U[j]
            L[i+1,j] = m 
    return (L,U)

In [104]:
A = np.array([[2, 3, 1, 5], 
              [1, 3.5, 1, 7.5],
              [1.4, 2.7, 5.5, 12],
              [-2, 1, 3, 28]])

b = np.array([11, 13, 21.6, 30])

# por eliminação de Gauss
x = gaussElimin(A.copy(), b.copy())
print(x)


# por eliminação de Gauss-Jordan
M = gaussJordan(np.hstack([A.copy(), b.reshape(len(A), 1)]))
x = M[:, -1] # última coluna
print(x)

# decomposição LU
L, U = fatoraLU(A.copy())
y = solve_tril(L,b)
x = solve_triu(U,y)
print(x)

# matriz inversa
Ainv = gaussJordan(np.hstack([A, np.identity(len(A))]))

x = Ainv[:, len(A):] @ b
print(x)

# linalg solve
x = np.linalg.solve(A.copy(), b)
print(x)

[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]


**2.** ([Burden et al, 2016, p. 420](https://integrada.minhabiblioteca.com.br/reader/books/9788522123414/pageid/436)) Resolva o seguinte sistema linear por eliminação de Gauss, eliminação de Gauss-Jordan e usando matriz inversa.

$$
\begin{aligned}
1,19 x_1+2,11 x_2-100 x_3+x_4 & =1,12 \\
14,2 x_1-0,122 x_2+12,2 x_3-x_4 & =3,44 \\
100 x_2-99,9 x_3+x_4 & =2,15 \\
15,3 x_1+0,110 x_2-13,1 x_3-x_4 & =4,16
\end{aligned}
$$


In [107]:
A = np.array([[1.19, 2.11, -100, 1], 
              [14.2, -0.122, 12.2, -1],
              [0, 100, -99.9, 1],
              [15.3, 0.110, -13.1, -1]])

b = np.array([1.12, 3.44, 2.15, 4.16])

# por eliminação de Gauss
x = gaussElimin(A.copy(), b.copy())
print(x)


# por eliminação de Gauss-Jordan
M = gaussJordan(np.hstack([A.copy(), b.reshape(len(A), 1)]))
x = M[:, -1] # última coluna
print(x)

# matriz inversa
Ainv = gaussJordan(np.hstack([A, np.identity(len(A))]))

x = Ainv[:, len(A):] @ b
print(x)

# linalg solve
x = np.linalg.solve(A.copy(), b)
print(x)

[ 0.1768253   0.01269269 -0.02065405 -1.1826087 ]
[ 0.1768253   0.01269269 -0.02065405 -1.1826087 ]


**3.** ([Burden et al, 2016, p.455](https://integrada.minhabiblioteca.com.br/reader/books/9788522123414/pageid/471)) Use fatoração LU para resolver o sistema linear a seguir. 

$$
\begin{aligned}
2 x_1+x_2 & =0, \\
-x_1+3 x_2+3 x_3 & =5, \\
2 x_1-2 x_2+x_3+4 x_4 & =-2, \\
-2 x_1+2 x_2+2 x_3+5 x_4 & =6 .
\end{aligned}
$$

In [127]:
from scipy.linalg import lu

A = np.array([[2, 1, 0, 0], 
              [-1, 3, 3, 0],
              [2, -2, 1, 4],
              [-2, 2, 2, 5]], float)

b = np.array([0, 5, -2, 6], float)


# por eliminação de Gauss
x = gaussElimin(A.copy(), b.copy())
print(x)


# por eliminação de Gauss-Jordan
M = gaussJordan(np.hstack([A.copy(), b.copy().reshape(len(A), 1)]))
x = M[:, -1] # última coluna
print(x)

# matriz inversa
Ainv = gaussJordan(np.hstack([A, np.identity(len(A))]))

x = Ainv[:, len(A):] @ b
print(x)

# decomposição LU
L, U = fatoraLU(A.copy())
y = solve_tril(L,b.copy())
x = solve_triu(U,y.copy())
print(x)

# scipy linalg.lu
L2, U2 = lu(A.copy(), permute_l=True)
y = solve_tril(L2,b.copy())
x = solve_triu(U2,y.copy())
print(x)


# linalg solve
x = np.linalg.solve(A.copy(), b)
print(x)

[-0.61702128  1.23404255  0.22695035  0.36879433]
[-0.61702128  1.23404255  0.22695035  0.36879433]
[-0.61702128  1.23404255  0.22695035  0.36879433]
[-0.61702128  1.23404255  0.22695035  0.36879433]
[-0.61702128  1.23404255  0.22695035  0.36879433]
[-0.61702128  1.23404255  0.22695035  0.36879433]
